### ISSUE TITLE
Still only seeing 0.15.2 on brew

### ISSUE THREAD

**Issue by kaspnilsson** [bazelbuild/homebrew-tap#6] opened 2018-09-19 17:43 UTC
Following the instructions in the readme, I get the output:

```
brew tap bazelbuild/tap 
brew tap-pin bazelbuild/tap
brew install bazel
==> Pinned bazelbuild/tap
To restore the stashed changes to /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git stash pop'
Warning: bazel 0.15.2 is already installed and up-to-date
To reinstall 0.15.2, run `brew reinstall bazel`
```

**Comment by buchgr** [comment] 2018-09-19 18:38
@kaspnilsson you probably have Bazel from homebrew-core installed. Please `brew uninstall bazel` first. I ll update the README with special instructions. Thanks!

**Comment by Globegitter** [comment] 2018-09-20 08:57
@buchgr I am running into the same issue and I tried running `brew uninstall bazel`. It did not change anything.

**Comment by kaspnilsson** [comment] 2018-09-20 17:16
Yup, same here. Running `brew install bazelbuild/tap/bazel` worked though. Maybe there's something wrong with the tap-pin?

**Comment by therc** [comment] 2018-09-20 19:57
Same for me. And the more verbose install command works for me, too.

**Comment by buchgr** [comment] 2018-09-26 15:51
Which versions of macOS are you running? We are seeing some reports that it stopped working on 10.14.

**Comment by buchgr** [comment] 2018-09-27 12:36
Hmm. I am getting a much more verbose output that @kaspnilsson 

```
$ brew tap bazelbuild/tap
==> Tapping bazelbuild/tap
Cloning into '/Users/buchgr/homebrew/Library/Taps/bazelbuild/homebrew-tap'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Tapped 1 formula (32 files, 40.6KB).

$ brew tap-pin bazelbuild/tap
==> Pinned bazelbuild/tap

$ brew install bazel
Warning: bazel is provided by core, but is now shadowed by bazelbuild/tap/bazel.
To refer to the core formula, use Homebrew/core/bazel instead.
==> Installing bazel from bazelbuild/tap
==> Downloading https://releases.bazel.build/0.17.2/release/bazel-0.17.2-installer-darwin-x86_64.sh
Already downloaded: /Users/buchgr/Library/Caches/Homebrew/downloads/2bb42b648c9e67f8456ad996890327821567f9784a8721946834ce20f8ff2c22--bazel-0.17.2-installer-darwin-x86_64.sh
==> chmod 0555 ./bazel-0.17.2-installer-darwin-x86_64.sh
==> ./bazel-0.17.2-installer-darwin-x86_64.sh --prefix=/private/tmp/bazel-20180927-39909-t5ve2g
==> Caveats
Bash completion has been installed to:
  /Users/buchgr/homebrew/etc/bash_completion.d
==> Summary
🍺  /Users/buchgr/homebrew/Cellar/bazel/0.17.2: 5 files, 163.0MB, built in 9 seconds
```

**Comment by buchgr** [comment] 2018-09-28 12:08
I have tried some more with a fresh homebrew installation and I am still unable to reproduce. I have tried:
1. First install Bazel from core, uninstall, install Bazel from bazelbuild/tap.
2. Directly install Bazel from bazelbuild/tap

Both of these worked flawlessly for me :(

**Comment by philwo** [comment] 2018-10-30 20:09
This happened again on my personal machine. I can repro it here now, so I'm going to file a bug with Homebrew. Maybe they have an idea what's going on.

**Comment by philwo** [comment] 2018-10-30 20:10
Filed an issue: https://github.com/Homebrew/brew/issues/5218

**Comment by philwo** [comment] 2018-11-19 17:46
I think this was fixed by a recent Homebrew upgrade. If it happens again, please comment and we'll reopen this!

**Closed by philwo** 2018-11-19 17:46 UTC
